version: '3.8'
services:
  db:
    image: postgres:15
    container_name: book-store-db
    restart: always
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Kyiv
      PGTZ: Europe/Kyiv
    ports:
      - "5433:5432"
    command: postgres -c timezone=Europe/Kyiv
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
